// Real public signals for each company — used to derive usage estimates and onboarding stages
// Every field has a source. Nothing guessed.

export const COMPANY_SIGNALS = {
  "Notion": {
    relationship: "Customer / Managed Agents early adopter",
    first_announced: "2026-01", // Code with Claude conference, Managed Agents launch
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Early Managed Agents customer — deployed agents across project management, HR, finance, software dev",
    engineering_blog: false,
    hiring_claude: true, // AI/ML roles mentioning LLM integration
    inferred_stage: "champion",
    stage_evidence: "Featured customer story on claude.com, early Managed Agents adopter, deployed across multiple business functions",
    sources: ["https://venturebeat.com/infrastructure/anthropic-embeds-slack-figma-and-asana-inside-claude-turning-ai-chat-into-a"],
  },
  "Slack": {
    relationship: "Customer + MCP Integration Partner",
    first_announced: "2026-01", // MCP app integration launch
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Two-way MCP integration; Claude for AI search and summaries",
    engineering_blog: false,
    hiring_claude: true,
    inferred_stage: "scaling",
    stage_evidence: "Active MCP integration, featured case study, but no public deployment numbers or engineering blog post yet",
    sources: ["https://techcrunch.com/2026/01/26/anthropic-launches-interactive-claude-apps-including-slack-and-other-workplace-tools/"],
  },
  "HubSpot": {
    relationship: "Customer / Case Study",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Product and marketing leaders using Claude Cowork; 'reclaims time for creativity'",
    engineering_blog: false,
    hiring_claude: true,
    inferred_stage: "scaling",
    stage_evidence: "Multiple case studies (Cowork + general), leadership publicly endorsing, but no deployment scale numbers",
    sources: ["https://claude.com/customers"],
  },
  "Twilio": {
    relationship: "Customer / Case Study",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "PM built 'self-learning development platform' with Claude Code",
    engineering_blog: false,
    hiring_claude: true,
    inferred_stage: "integrated",
    stage_evidence: "Case study focused on single PM use case, not org-wide deployment. Suggests department-level adoption, not company-wide.",
    sources: ["https://claude.com/customers"],
  },
  "Figma": {
    relationship: "Customer + Deep Integration Partner",
    first_announced: "2025-H2", // MCP integration, then Claude Design Apr 2026
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Interactive app integration in Claude; co-developed Claude Design (Apr 2026)",
    engineering_blog: false,
    hiring_claude: true,
    inferred_stage: "champion",
    stage_evidence: "Co-developed Claude Design product, deep MCP integration, featured customer. Product-level partnership beyond just using the API.",
    sources: ["https://thenextweb.com/news/canva-anthropic-claude-design-ai-powered-visual-suite"],
  },
  "PwC": {
    relationship: "Claude Partner Network Anchor",
    first_announced: "2025-12", // Expanded partnership announcement
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "30,000 professionals to be trained/certified; joint Center of Excellence; new 'Office of the CFO' business unit built on Claude",
    engineering_blog: false,
    hiring_claude: true,
    deployment_seats: 30000,
    estimated_annual_spend: "$50M-$150M (scaling to $300M+)",
    spend_source: "30K certified × estimated $140-$415/seat/mo (seat + API consumption)",
    inferred_stage: "scaling",
    stage_evidence: "30K certifications is massive but 'to be trained' language suggests still rolling out. New business unit = scaling, not yet champion.",
    sources: ["https://www.anthropic.com/news/pwc-expanded-partnership", "https://www.pwc.com/us/en/about-us/newsroom/press-releases/anthropic-pwc-expand-alliance-agentic-enterprise.html"],
  },
  "Accenture": {
    relationship: "Claude Partner Network Anchor",
    first_announced: "2025-12", // Multi-year partnership Dec 2025
    case_study: false,
    public_scale: "30,000 professionals trained; dedicated Anthropic Business Group; multi-year deal; focus on regulated industries",
    engineering_blog: false,
    hiring_claude: true,
    deployment_seats: 30000,
    estimated_annual_spend: "$50M-$150M (scaling)",
    spend_source: "30K trained, dedicated business group, multi-year commitment",
    inferred_stage: "champion",
    stage_evidence: "Dedicated Anthropic Business Group, 30K trained (past tense vs PwC's future tense), multi-year commitment. They're deploying to clients, not just internal.",
    sources: ["https://www.anthropic.com/news/anthropic-accenture-partnership"],
  },
  "Jamf": {
    relationship: "Customer",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "No deployment numbers published",
    engineering_blog: false,
    hiring_claude: false, // No Claude-specific job postings found
    inferred_stage: "integrated",
    stage_evidence: "Has a case study but no public scale numbers, no Claude-specific hiring. Suggests steady but not aggressive adoption.",
    sources: ["https://claude.com/customers"],
  },
  "Smartsheet": {
    relationship: "Customer",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "No deployment numbers published",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "first_workflow",
    stage_evidence: "Case study exists but minimal public signal beyond that. No engineering blog, no hiring for Claude roles, no deployment numbers. Early-stage adoption.",
    sources: ["https://claude.com/customers"],
  },
  "Pendo": {
    relationship: "Customer Q&A",
    first_announced: "2026-Q1",
    case_study: true, // Q&A format
    case_study_url: "https://claude.com/customers",
    public_scale: "No deployment numbers published",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "integrated",
    stage_evidence: "Q&A case study format (less depth than full case study). Suggests active usage but not at scale.",
    sources: ["https://claude.com/customers"],
  },
  "ChatPlace": {
    relationship: "Customer / Case Study",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "'Gives solo creators an AI marketing team with Claude' — Claude is core to their product",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "champion",
    stage_evidence: "Claude IS their product. Built their entire offering on Claude API. That's champion for a startup.",
    sources: ["https://claude.com/customers"],
  },
  "OpusClip": {
    relationship: "Customer",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Video AI platform using Claude for content understanding",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "scaling",
    stage_evidence: "Customer story published, Claude integrated into product, but no public deployment scale numbers.",
    sources: ["https://claude.com/customers"],
  },
  "Brainlabs": {
    relationship: "Customer",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Digital marketing agency using Claude for campaign optimization",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "integrated",
    stage_evidence: "Case study but no scale signals. Agency model suggests team-level adoption.",
    sources: ["https://claude.com/customers"],
  },
  "Syracuse University": {
    relationship: "Campus Partner",
    first_announced: "2025-09", // Among first Claude for Education partners
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "Campus-wide access for all students, faculty, staff",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "scaling",
    stage_evidence: "Campus-wide rollout announced Sep 2025 — 8+ months in, should be well into adoption. But education adoption cycles are slow.",
    sources: ["https://news.syr.edu/2025/09/22/syracuse-university-among-first-universities-to-provide-campuswide-ai-access-to-anthropics-claude-for-education/"],
  },
  "YMCA South Australia": {
    relationship: "Customer",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "No deployment numbers. Small org.",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "first_api_call",
    stage_evidence: "Customer story exists but YMCA SA is a small nonprofit. Likely minimal technical adoption. High churn risk without support.",
    sources: ["https://claude.com/customers"],
  },
  "Satispay": {
    relationship: "Customer",
    first_announced: "2026-Q1",
    case_study: true,
    case_study_url: "https://claude.com/customers",
    public_scale: "European fintech / payments company",
    engineering_blog: false,
    hiring_claude: false,
    inferred_stage: "integrated",
    stage_evidence: "Case study published. Fintech suggests API integration for product features. No public scale numbers.",
    sources: ["https://claude.com/customers"],
  },
};

// Spend estimation methodology
// Source: Public pricing (docs.anthropic.com/pricing), Uber CTO disclosure ($500-$2K/eng/mo),
// PwC/Accenture seat counts (30K each), Snowflake deal ($200M multi-year)
export const SPEND_MODEL = {
  methodology: "Bottom-up from public pricing × estimated seats × utilization rate. Cross-referenced with disclosed deal sizes where available.",
  assumptions: {
    enterprise_seat_cost: "$20/seat/mo base",
    avg_api_consumption_per_developer: "$150-$250/mo (Claude Code heavy usage, per Uber CTO disclosure)",
    avg_api_consumption_per_knowledge_worker: "$30-$80/mo (Cowork/chat usage)",
    cache_savings_applied: "30% average (most enterprises underutilize caching per GitHub signal)",
    batch_adoption: "10-15% of workloads (low adoption per token health analysis)",
  },
  sources: [
    "docs.anthropic.com/en/docs/about-claude/pricing",
    "Uber CTO: $500-$2K/engineer/month (briefs.co)",
    "PwC: 30K certifications (anthropic.com/news)",
    "Accenture: 30K trained (anthropic.com/news)",
    "Snowflake: $200M multi-year (snowflake.com)",
    "Anthropic: <5% hit weekly limits (x.com/AnthropicAI)",
  ],
};
